project:
  # takes the following values:
  # * 'book': publishes output to docs/_book/
  # * 'website': publishes output to docs/_site/
  type: website

# if project.type = 'website' value set to 'navbar' or 'sidebar'
# if project.type = 'book' value set to 'chapters'

website:
  title: "SRE Playbooks – Proxmox"
  sidebar:
    search: true
    contents:
      - index.qmd
      - section: "🔥 Incident Reviews"
        contents:
          - incident-reviews/unlock_pve_vms.qmd
          - incident-reviews/ha_fencing_loop.qmd
      - section: "📖 Runbook Explanations"
        contents:
          - runbook-explanation/unlock_pve_vms.qmd
          - runbook-explanation/ha_fencing_loop.qmd


# book:
#   title: "SRE Playbooks – Proxmox"
#   author: "Amine GmbH"
#   date: today
#   chapters:
#     - index.qmd
#     - part: "Runbook Explanations"
#       chapters:
#         - runbook-explanation/unlock_pve_vms.qmd
#     - part: "Incident Reviews"
#       chapters:
#         - incident-reviews/unlock_pve_vms.qmd

format:
  html:
    theme: cosmo       # or darkly, flatly, etc.
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-tools: true

execute:
  freeze: auto         # cache outputs to avoid re-running on every render
