name: Cleanup Github Pages PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v6
        with:
          ref: gh-pages

      - name: Remove preview folder
        run: |
          if [ -d "previews/pr-${{ github.event.number }}" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git rm -rf "previews/pr-${{ github.event.number }}"
            git commit -m "chore: remove preview for PR #${{ github.event.number }}"
            git push
          else
            echo "No preview folder found, skipping."
          fi
